sender: "gintonewsletter@outlook.com"
recipients: ["guidallemagne@hotmail.com", "jeremykichat@hotmail.fr"] #TODO needs to come from secret
outlook_smtp: "smtp-mail.outlook.com"
file_name: "Newsletter GinTo (Responses)"