sender: "gintonewsletter@outlook.com"
recipients: ["guidallemagne@hotmail.com", "jeremy.minet.97@hotmail.com"]
subject: "Test email via Rscript - form link"
pw: "bouzoulewifi69"
outlook_smtp: "smtp-mail.outlook.com"
form_url: "https://forms.gle/LMMjeNuUFEE3u48y8"
json_path: "eclusenewletter-0185910f7bbf.json"
file_name: "Newsletter GinTo (Responses)"
