on:
  push:
    branches: main #TODO: eventually remove this line, for testing purpose
  schedule:
    - cron: '0 16 * * *' #Every day at 4 PM
jobs:
  call-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googlesheets4
            any::glue
            any::mailR
            any::yaml
            any::googledrive

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Send weekly email
        env:
          MAIL_PWD: ${{ secrets.MAILPWD }}
        run: Rscript -e 'source("weekly_task.R")'
        
      #- name: Send monthly email
      #  env:
      #    SA_SECRET: ${{ secrets.SA_SECRET }}
      #  run: Rscript -e 'source("monthly_task.R")'