on:
  push:
    branches: main
  schedule:
    - cron: '*/10 * * * *'
jobs:
  call-r-script:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::googlesheets4
            any::glue
            any::mailR

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import data
        env:
          MAIL_PWD : ${{ secrets.MAILPWD }}
        run: Rscript -e 'source("send_mail.R")'